server:
  servlet:
    context-path: /
  port: 8000
spring:
  application:
    name: retailer_service
  datasource:
    url: jdbc:h2:mem:retailerService
    driveClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true